name: Reclaim
description: "help reclaim your time and focus."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0 # Crucial for that "smooth" Gen Z feel
  intl: ^0.18.1
  glassmorphism: ^3.0.0 # Optional, but adds nice style
  audioplayers: ^6.5.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/


