name: Reclaim
description: "help reclaim your time and focus."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0 # Crucial for that "smooth" Gen Z feel
  intl: ^0.18.1
  glassmorphism: ^3.0.0 # Optional, but adds nice style
  audioplayers: ^6.5.1
  fl_chart: ^1.1.1
  flutter_dotenv: ^5.2.1
  youtube_player_flutter: ^9.1.3
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#050505"
    theme_color: "#B4F8C8"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - .env


